### PR TITLE
Refactor README with more straightforward instructions

### PR DESCRIPTION
**Pull request by manuelma**
Re #1232

Cc @PekkaSavolainen 

The idea here is to be quite explicit about the instructions we ask the users to perform. This is so we don't need to be answering questions like "What do you mean by cloning?", or "Am I at the correct place?", which basically defeats the point of having a README which is for us *not to have to be answering any questions*.

If something goes wrong, this also removes one debugging step, which is one of us asking, "Ok, what exactly did you do to get to this issue?" Since the steps are cleared out from the beginning, we can jump directly to asking what is their platform, and then running the steps in that platform ourselves.

### CODE REVIEW

**Comment by PekkaSavolainen** [comment]
It's a good improvement. Our goal has been to write the readme for dummies and that's why there's, for example, the link that specifically tells people what cloning means. I guess over time the readme has grown too much and it's too hard to find the instructions that matter so it's good to do the cleanup here.

But what do we say to users who answer the question "Do you have Conda?" No, and I don't want it because I don't know what it is? (I guess they can use the installation bundles, so not a biggie).

Two small addons:

1. How about adding a mention about spine_items in the **About requirements**. That package is quite important these days.
2. **Building the User Guide** should begin with something like: "You can find the latest documentation on readthedocs. If you want to build the documentation yourself, ... <current text>". Where, readthedocs is of course a link to the latest docs. 

That Anaconda Prompt picture is good 😄

**Comment by manuelma** [comment]
> the link that specifically tells people what cloning means

Yeah I got rid of that. Do we want them back?

> "Do you have Conda?" No, and I don't want it because I don't know what it is?

Good point... I guess the answer is as you say, use the Windows installer. But I don't expect too many people asking that...do you? Maybe we can pitch Conda a little bit, like it's a great package manager, THE greatest package manager for the greatest language...?

**Comment by PekkaSavolainen** [comment]
> Yeah I got rid of that. Do we want them back?

Nah, it was a bit condescending.

The repercussion of this change is that people who don't yet have conda, I think 95% of them will install Anaconda because that's mentioned before miniconda. I propose we nudge the users towards miniconda by simply switching the order of the Anaconda and Miniconda links. Although we should be ready for anaconda environments after #1230 but just to be sure.

**Comment by manuelma** [comment]
Thanks @PekkaSavolainen 

I added your suggestions. I propose we merge and close the issue? Or you have some more remarks?

**Pull request merged**
