### PR TITLE
Looping

### LINKED ISSUE #329: Support looping via sub-DAG's
In GitLab by @PekkaSavolainen on Sep 25, 2019, 15:16

Create a new 'project item' that can be used to run Tool items iteratively until some condition has been met.

### PR DESCRIPTION
**Pull request by soininen**
This and its companion PR Spine-project/Spine-Engine#39 together implement loops in Spine Toolbox.

In Toolbox, it is now possible to connect project items with a special *Loop link* that creates a conditional jump in the dag. Currently, loop condition (continue or break?) is implemented as a user given Python script which should allow for maximum flexibility. The script is also somewhat cumbersome and counterintuitive to use so more work on this is expected in the future but not in scope of this PR.

If Engine is supplied with jumps, it will break the DAG into *chunks* at jump end points that are executed one after the other. A loop is a chunk that is executed as many times as its condition dictates (but always at least once).

**Todo:**

- [x] Implement nested loops
- [x] Update release notes

**Limitations**

It is not possbile to create overlapping loops except nested ones.

**Benchmarking**

A project with ~40 Data connections forming a branching DAG was used to gauge the performance impact when no loops are present. Since we basically use the same mechanism for such DAGs as we do on `master` no impact was expected. Turns out there was some and that is due to dagster 0.11 internals being noticeably slower than in 0.10.

**To test:**

Note, that you'll need to upgrade dagster to 0.11 for this!

1. Checkout this and perhaps Spine-project/Spine-Engine#39 branch
2. Upgrade requirements, should upgrade dagster as well
3. Start Toolbox
4. Check that your existing projects execute as before

1. Create Loop links between project items by holding **Alt** key while clicking the source items (loop's end point) connector button
2. Click a Loop link and edit its condition script. E.g. to execute a loop a given number of times, you can try the following:

```python
import sys
counter = int(sys.argv[1])  # Loop counter is supplied as first command line argument
exit(0 if counter < 3 else 1)  # Exit code 0 = continue, anything else = break
```

7. Execute the project. You should see from item's Execution logs that it gets executed multiple times
8. Try breaking looping by creating crazy Loop links or condition scripts

Resolves #329,

### CODE REVIEW

**Comment by manuelma** [comment]
Nice! Can we have some implementation details? Nothing big, just a couple of lines about what's the direction taken and the main changes?

**Comment by soininen** [comment]
> Can we have some implementation details?

I'll be happily using 'jump' and 'loop' interchangably below.

In the Engine side, loops are represented by `Jump` objects which share a new base class `ConnectionBase` with `Connection`s. If engine's `__init__()` receives any jumps, it will break the forward-execution pipeline into *chunks*. In case of a single jump, the first chunk would contain items up to the jump's source (including items in the loop), second chunk would have jump's items while the third chunk would have all the rest. Note that in this setup the loop gets executed at least once since otherwise we might run intro trouble with missing resources after the loop.

`Engine.run()` now has two branches: if there are no jumps then we execute as before. In case of jumps, we execute in parts using `reexecute_pipeline_iterator()` instead of `execute_pipeline_iterator()` which allows partial execution. First, all backward solids are executed to resolve backward resources. Then we execute the chunks one-by-one in loops; if there is a jump condition associated with a chunk (it is actually a loop) then the chunk gets executed as many times as the condition passes.

Currently, jump condition is a Python script that is run in Toolbox's Python interpreter as a subprocess. The process's return value is used to declare whether to jump or not.

When upgrading dagster to 0.11, I had to rewrite parts of multithread executor. We also use a custom in-memory IO manager now.

In Toolbox side I guess the main addition was integration of `Jump` into `SpineToolboxProject` and `JumpLink` which is a new link for Design view.

**Comment by manuelma** [comment]
Thank you very much @soininen, this seems really good then. TUDelft will be happy.

> We also use a custom in-memory IO manager now.

I'm curious about this. I guess we need it so chunks can share resources?

> Turns out there was some and that is due to dagster 0.11 internals being noticeably slower than in 0.10.

Should we open an issue with dagster?

**Comment by soininen** [comment]
> I'm curious about this. I guess we need it so chunks can share resources?

Indeed, we need a 'persistent' storage to carry item resources over different chunks, i.e. between calls to `reexecute_pipeline_iterator()`. On top of that it seems that with dagster 0.11, an IO manager is needed to share resources between threads in our multi-threaded executor.

Initially I used dagster's build in `fs_io_manager` which pickles objects to file system. There were concerns that it might have some overhead, though, so I tried replacing it with our own in-memory implementation. The speed-up turned out to be meagre at best but the in-memory IO manager is such a simple piece of code that I think we can let it stay.

> Should we open an issue with dagster?

If the extra overhead feels like too much, then we should really consider doing that.

**Pull request merged**
