### PR TITLE
Add two new tutorials for short-term hydro power planning

### PR DESCRIPTION
**Pull request by iasonask**

### CODE REVIEW

**Comment by ererkka** [comment]
The docs build fine, that’s all right. 

Could the two tutorials _Case Study A5 tutorial_ and _Case Study A5 tutorial using the Importer_ be merged so that the importer phase would be an optional step? Now I think there is a lot of overlap in these two, and if they need to be updated someday, it will be painful to make the changes in both.

**Comment by ererkka** [comment]
Did you have someone else go through the tutorials for sanity check? @iasonask

**Comment by iasonask** [comment]
Yes, they have been reviewed. Also, I'll try to merge them as you suggest, I agree it's a good idea.

**Comment by ererkka** [comment]
Better like this, but I find that there is a lot of overlapping content in the A5 tutorial still. What if the structure was like this:
1. Introduction: as it is now
2. Installing requirements: drop heading ‘Guide’ and bring these to top level
3. Creating a new project
4. Entering data: present two alternative options
    4a. Manually: current ‘Entering input data’
    4b. Using an Importer: current ‘Using the Importer’, ‘Importing raw data with the importer’ and ‘Importing the SpineOpt database template’
5. Executing the workflow
6. Examining the results (as it is now, but just once)

**Comment by iasonask** [comment]
Thanks, I changed it, check now

**Review by ererkka — APPROVED** [review]

**Pull request merged**
